### ISSUE TITLE
忽略过期证书提醒

### ISSUE THREAD

**Issue by qcgzxw** [idawnlight/qcloud-lets-encrypt#6]
[SSL证书API概览](https://cloud.tencent.com/document/product/400/41681)

[修改是否忽略证书到期通知](https://cloud.tencent.com/document/api/400/82277)

每次替换完，旧证书还是一直发邮件提醒。
我前段时间提交反馈让腾讯云加了API，现在可以通过API关闭某个证书的提醒。
可以在申请的同时，调用接口忽略旧证书提醒。

**Comment by idawnlight** [comment]
目前在域名配置中新增了 `disableExpireNotification` 选项，如果为 `true` 会禁用当前域名正在使用的证书的过期提醒。

https://github.com/idawnlight/qcloud-lets-encrypt/blob/0a59dfd67a6eb0fee5ce9d46078455186bead556/config.example.php#L18

暂时还未测试，请谨慎使用。

**Comment by qcgzxw** [comment]
太快了吧！感谢，我用上试试
