### ISSUE TITLE
手动执行命令后，提示 Undefined offset: 0

### ISSUE THREAD

**Issue by miaomiaocatmsg** [idawnlight/qcloud-lets-encrypt#7]
New cert 3r8NTaVP.
Undefined offset: 0

能返回证书id，腾讯云cdn的证书也能上传成功，但是不会自动替换上传的证书，不知是哪里出了问题
php7.2
秘钥是最高权限的那个

**Comment by idawnlight** [comment]
请检查配置文件中的域名是否与腾讯云 CDN 上正在使用的域名完全一致，这里的报错应该是腾讯云 CDN 的 `DescribeDomainsConfig` 接口没有返回有效的信息，即没有找到对应的域名。

**Comment by miaomiaocatmsg** [comment]
> 请检查配置文件中的域名是否与腾讯云 CDN 上正在使用的域名完全一致，这里的报错应该是腾讯云 CDN 的 `DescribeDomainsConfig` 接口没有返回有效的信息，即没有找到对应的域名。

仔细排查过了，域名完全一致，并且所有域名下，证书也是上传成功的， 返回的 New cert 3r8NTaVP. id也是正确的

**Comment by miaomiaocatmsg** [comment]
> 请检查配置文件中的域名是否与腾讯云 CDN 上正在使用的域名完全一致，这里的报错应该是腾讯云 CDN 的 `DescribeDomainsConfig` 接口没有返回有效的信息，即没有找到对应的域名。

排查完毕~解决问题。辛苦啦~
